import pandas as pd
import numpy as np

def generate_rfm_summary(fin_df):
    """
    Evaluates raw financial data at the individual player level to determine their status and behavior profile.
    Calculates Lifetime_GGR, Total_Deposits, and identify the most recent report_month (Recency).
    Flags users with Lifetime_GGR >= 500 as 👑 True VIP.
    """
    if fin_df.empty:
        return pd.DataFrame()
        
    # Safe handling for columns that might not exist in standard adapter
    agg_dict = {
        'revenue': 'sum',
        'bet': 'sum',
        'deposits': 'sum',
        'report_month': ['min', 'max', 'nunique'],
        'brand': 'first',
        'country': 'first'
    }
    
    if 'ngr' in fin_df.columns: agg_dict['ngr'] = 'sum'
    if 'bonus_total' in fin_df.columns: agg_dict['bonus_total'] = 'sum'
    if 'withdrawals' in fin_df.columns: agg_dict['withdrawals'] = 'sum'
    if 'deposit_count' in fin_df.columns: agg_dict['deposit_count'] = 'sum'

    rfm_df = fin_df.groupby('id').agg(agg_dict).reset_index()

    # Flatten the hierarchical columns generated by agg
    rfm_columns = [
        'id', 'Lifetime_GGR', 'Lifetime_Turnover', 'Lifetime_Deposits',
        'First_Month', 'Last_Month', 'Months_Active',
        'brand', 'country'
    ]
    if 'ngr' in fin_df.columns: rfm_columns.append('Lifetime_NGR')
    if 'bonus_total' in fin_df.columns: rfm_columns.append('Lifetime_Bonus')
    if 'withdrawals' in fin_df.columns: rfm_columns.append('Lifetime_Withdrawals')
    if 'deposit_count' in fin_df.columns: rfm_columns.append('Lifetime_Deposit_Count')

    rfm_df.columns = rfm_columns


    # Recency: Months Inactive calculation
    # We find the max report_month across the entire dataset to determine the "Current Month"
    current_month_global = fin_df['report_month'].max()
    
    # Calculate difference in months between the global max month and the player's last active month
    def diff_month(d1_str, d2_str):
        try:
            d1 = pd.to_datetime(d1_str)
            d2 = pd.to_datetime(d2_str)
            return (d1.year - d2.year) * 12 + d1.month - d2.month
        except:
            return 0
            
    rfm_df['Months_Inactive'] = rfm_df['Last_Month'].apply(lambda x: diff_month(current_month_global, x))
    
    # Compute average monthly turnover
    rfm_df['Avg_Monthly_Turnover'] = np.where(rfm_df['Months_Active'] > 0, rfm_df['Lifetime_Turnover'] / rfm_df['Months_Active'], 0)
    
    # To determine Last_Month_Turnover, we can map it back from the original df based on ID and Last_Month 
    last_month_records = fin_df.sort_values('report_month').drop_duplicates('id', keep='last')
    last_month_map = dict(zip(last_month_records['id'], last_month_records['bet']))
    rfm_df['Last_Month_Turnover'] = rfm_df['id'].map(last_month_map).fillna(0)

    # Calculate Tenure_Months
    rfm_df['Tenure_Months'] = rfm_df.apply(lambda row: diff_month(row['Last_Month'], row['First_Month']) + 1, axis=1)

    # Flag True VIP
    rfm_df['Is_VIP'] = rfm_df['Lifetime_GGR'] >= 500

    return rfm_df

def generate_smart_profiles(rfm_df):
    """
    Applies the strict 7-tier heuristic array to the grouped dataframe based on SPEC rules:
    - 🏆 Ironman Legend
    - 👑 Active Crown Jewel
    - 📉 Cooling Down (Velocity Risk)
    - 🛑 Promo Exclusion (Risk)
    - 🚨 Early Churn VIP
    - 🌟 Rising Star
    - 🎯 Cold Crown Jewel
    - ✉️ Standard Lifecycle
    """
    if rfm_df.empty:
        return pd.DataFrame()
        
    def determine_profile(row):
        # 1. Ironman Legend Evaluate BEFORE Active Crown Jewel
        if row['Months_Active'] >= 6 and row['Months_Inactive'] == 0 and row['Months_Active'] == row['Tenure_Months']:
            return "🏆 Ironman Legend"
            
        # 2. Active Crown Jewel
        if row['Lifetime_GGR'] >= 1000 and row['Months_Inactive'] == 0:
            return "👑 Active Crown Jewel"
            
        # 3. Cooling Down (Velocity Risk)
        if row['Months_Inactive'] == 0 and row['Last_Month_Turnover'] < (row['Avg_Monthly_Turnover'] * 0.5) and row['Lifetime_Turnover'] >= 1000:
            return "📉 Cooling Down (Velocity Risk)"
            
        # 4. Promo Exclusion (Risk)
        if row['Lifetime_GGR'] < 0 and row['Lifetime_Turnover'] > 5000:
            return "🛑 Promo Exclusion (Risk)"
            
        # 5. Early Churn VIP
        if row['Months_Inactive'] == 1 and row['Lifetime_GGR'] > 500:
            return "🚨 Early Churn VIP"
            
        # 6. Rising Star
        if row['Months_Active'] <= 2 and row['Lifetime_Turnover'] > 1000 and row['Months_Inactive'] == 0:
            return "🌟 Rising Star"
            
        # 7. Cold Crown Jewel
        if row['Months_Inactive'] >= 3 and row['Lifetime_GGR'] > 1000:
            return "🎯 Cold Crown Jewel"
            
        # 8. Standard Lifecycle
        return "✉️ Standard Lifecycle"

    profiles = rfm_df.copy()
    profiles['Smart_Profile'] = profiles.apply(determine_profile, axis=1)
    return profiles
