import pandas as pd
import numpy as np

def generate_rfm_summary(fin_df):
    """
    Evaluates raw financial data at the individual player level to determine their status and behavior profile.
    Calculates Lifetime_GGR, Total_Deposits, and identify the most recent report_month (Recency).
    Flags users with Lifetime_GGR >= 500 as 👑 True VIP.
    """
    if fin_df.empty:
        return pd.DataFrame()
        
    # Safe handling for columns that might not exist in standard adapter
    agg_dict = {
        'revenue': 'sum',
        'bet': 'sum',
        'deposits': 'sum',
        'report_month': ['min', 'max', 'nunique'],
        'brand': 'first',
        'country': 'first',
        'client': 'first'
    }
    
    if 'ngr' in fin_df.columns: agg_dict['ngr'] = 'sum'
    if 'bonus_total' in fin_df.columns: agg_dict['bonus_total'] = 'sum'
    if 'withdrawals' in fin_df.columns: agg_dict['withdrawals'] = 'sum'
    if 'deposit_count' in fin_df.columns: agg_dict['deposit_count'] = 'sum'

    rfm_df = fin_df.groupby('id').agg(agg_dict).reset_index()

    # Flatten the hierarchical columns generated by agg
    rfm_columns = [
        'id', 'Lifetime_GGR', 'Lifetime_Turnover', 'Lifetime_Deposits',
        'First_Month', 'Last_Month', 'Months_Active',
        'brand', 'country', 'client'
    ]
    if 'ngr' in fin_df.columns: rfm_columns.append('Lifetime_NGR')
    if 'bonus_total' in fin_df.columns: rfm_columns.append('Lifetime_Bonus')
    if 'withdrawals' in fin_df.columns: rfm_columns.append('Lifetime_Withdrawals')
    if 'deposit_count' in fin_df.columns: rfm_columns.append('Lifetime_Deposit_Count')

    rfm_df.columns = rfm_columns


    # Recency: Months Inactive calculation
    # We find the max report_month across the entire dataset to determine the "Current Month"
    current_month_global = pd.to_datetime(fin_df['report_month'].max())
    
    # Calculate difference in months between the global max month and the player's last active month
    # Vectorized computation
    lm = pd.to_datetime(rfm_df['Last_Month'])
    rfm_df['Months_Inactive'] = (current_month_global.year - lm.dt.year) * 12 + (current_month_global.month - lm.dt.month)
    rfm_df['Months_Inactive'] = rfm_df['Months_Inactive'].fillna(0).astype(int)
    
    # Compute average monthly turnover
    rfm_df['Avg_Monthly_Turnover'] = np.where(rfm_df['Months_Active'] > 0, rfm_df['Lifetime_Turnover'] / rfm_df['Months_Active'], 0)
    
    # Compute average deposit value (ADV)
    if 'Lifetime_Deposit_Count' in rfm_df.columns:
        rfm_df['Avg_Deposit_Value'] = np.where(rfm_df['Lifetime_Deposit_Count'] > 0, rfm_df['Lifetime_Deposits'] / rfm_df['Lifetime_Deposit_Count'], 0)
    else:
        rfm_df['Avg_Deposit_Value'] = 0
    
    # To determine Last_Month_Turnover, we can map it back from the original df based on ID and Last_Month 
    last_month_records = fin_df.sort_values('report_month').drop_duplicates('id', keep='last')
    last_month_map = dict(zip(last_month_records['id'], last_month_records['bet']))
    rfm_df['Last_Month_Turnover'] = rfm_df['id'].map(last_month_map).fillna(0)

    # Calculate Tenure_Months (vectorized)
    fm = pd.to_datetime(rfm_df['First_Month'])
    rfm_df['Tenure_Months'] = (lm.dt.year - fm.dt.year) * 12 + (lm.dt.month - fm.dt.month) + 1
    rfm_df['Tenure_Months'] = rfm_df['Tenure_Months'].fillna(1).astype(int)

    # Flag True VIP
    rfm_df['Is_VIP'] = rfm_df['Lifetime_GGR'] >= 500

    return rfm_df

def generate_smart_profiles(rfm_df):
    """
    Applies the strict 7-tier heuristic array to the grouped dataframe based on SPEC rules:
    - 🏆 Ironman Legend
    - 👑 Active Crown Jewel
    - 📉 Cooling Down (Velocity Risk)
    - 🛑 Promo Exclusion (Risk)
    - 🚨 Early Churn VIP
    - 🌟 Rising Star
    - 🎯 Cold Crown Jewel
    - ✉️ Standard Lifecycle
    """
    if rfm_df.empty:
        return pd.DataFrame()

    profiles = rfm_df.copy()
    
    conditions = [
        # 1. Ironman Legend Evaluate BEFORE Active Crown Jewel
        (profiles['Months_Active'] >= 6) & (profiles['Months_Inactive'] == 0) & (profiles['Months_Active'] == profiles['Tenure_Months']),
        # 2. Active Crown Jewel
        (profiles['Lifetime_GGR'] >= 1000) & (profiles['Months_Inactive'] == 0),
        # 3. Cooling Down (Velocity Risk)
        (profiles['Months_Inactive'] == 0) & (profiles['Last_Month_Turnover'] < (profiles['Avg_Monthly_Turnover'] * 0.5)) & (profiles['Lifetime_Turnover'] >= 1000),
        # 4. Promo Exclusion (Risk)
        (profiles['Lifetime_GGR'] < 0) & (profiles['Lifetime_Turnover'] > 5000),
        # 5. Early Churn VIP
        (profiles['Months_Inactive'] == 1) & (profiles['Lifetime_GGR'] > 500),
        # 6. Rising Star
        (profiles['Months_Active'] <= 2) & (profiles['Lifetime_Turnover'] > 1000) & (profiles['Months_Inactive'] == 0),
        # 7. Cold Crown Jewel
        (profiles['Months_Inactive'] >= 3) & (profiles['Lifetime_GGR'] > 1000)
    ]
    
    choices = [
        "🏆 Ironman Legend",
        "👑 Active Crown Jewel",
        "📉 Cooling Down (Velocity Risk)",
        "🛑 Promo Exclusion (Risk)",
        "🚨 Early Churn VIP",
        "🌟 Rising Star",
        "🎯 Cold Crown Jewel"
    ]
    
    profiles['Smart_Profile'] = np.select(conditions, choices, default="✉️ Standard Lifecycle")
    
    return profiles
